### PR TITLE
fix: resolve profile picture not showing on person page

### LINKED ISSUE #278: Profile picture not showing on person detail page
### Description

The main profile picture for actors/actresses is not displayed on the person detail page.

### To Reproduce

1. Navigate to any actor/actress page
2. Observe that the profile picture is missing

### Screenshot
<a href='https://postimg.cc/c6ggLfJZ' target='_blank'>image</a>

### Expected Behavior

The profile picture should be displayed properly on the person page.

### Device Info

* Device: Galaxy A20s
* OS: Android 11
* App Version: 1.2.4

### PR DESCRIPTION
**Pull request by waffiqaziz**
### Changes Made

- Reformat code to align with Klint
- Closes #278 

___

### **PR Type**
Other

___

### **Description**
- Refactor code to align with ktlint formatting rules

- Replace null-safe operators with `.orEmpty()` calls

- Convert multi-line functions to single expressions

- Remove redundant variable declarations and improve null handling

___

### Diagram Walkthrough

```mermaid
flowchart LR
  A["Code Files"] --> B["ktlint Rules"]
  B --> C["Formatting Changes"]
  C --> D["Null Safety Improvements"]
  C --> E["Expression Simplification"]
  C --> F["Code Cleanup"]
```

<details> <summary><h3> File Walkthrough</h3></summary>

<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><details><summary>19 files</summary><table>
<tr>
  <td><strong>RatedResponseAdapter.kt</strong><dd><code>Improve null handling in error logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-2158375d2227d2ed1662dce9b61d7c57741123ce9c812fabcb8a3d26e14205b6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>MovieDataSourceTest.kt</strong><dd><code>Remove redundant variable declarations in tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-0e2c8e758dd5a46b7ac3df655e22b590e91707c6135149bbf0658b2c5d8b162e">+0/-8</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>TrendingDataSourceTest.kt</strong><dd><code>Clean up unused imports and variables</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-00ccb74ca7f5fca5e6b09ba2b7b9a8dd3191290120ac08bd9691a5e6cd1fdbff">+0/-5</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>RatedResponseAdapterTest.kt</strong><dd><code>Extract helper method for assertion</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-33005df6a5fd77e0978ed65a2e96bd43ec7765cf60485113152a391ef75ca129">+9/-10</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>PagingDataHelperTest.kt</strong><dd><code>Convert methods to single expressions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-745913562082f06c4d002fc179bc88fbd3105f04a582cca4b9b10a382c8fc17a">+5/-9</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>UserPreference.kt</strong><dd><code>Replace null operators with orEmpty calls</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-6047755b241193cadae048ceac687021f4edd29e1996e15a88f82b3833716edb">+11/-11</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>RegionViewModel.kt</strong><dd><code>Use orEmpty for null safety</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-a034d4bd1475aa0653069c9ff7db4fc1cb1a1d4386e34992e42229042cb347ea">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>GenreHelper.kt</strong><dd><code>Replace null operator with orEmpty</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-f3e241370ca672963e2c65bcde48eb3240ed6c5e2c5d0e299950bb2d203551c6">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>GetRegionHelper.kt</strong><dd><code>Use orEmpty for locale country handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-4cc3f814601ad4e5f9bcb9b1e62ae46fb6a647cb1ec49f5e0d7bda03949642c7">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>MediaDetailActivityTrailerLinkTest.kt</strong><dd><code>Remove redundant nested activity launch</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-432a96743d7c36b262f0a414d54e4007d14643b0d70e8d554082d7f0a72094d0">+7/-9</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>RecommendationAdapter.kt</strong><dd><code>Convert DiffCallback methods to expressions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-8efb2527e162402f5299e8156550912329d0a240b9c0f088352715e9f626d6cb">+4/-12</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>AgeRatingHelper.kt</strong><dd><code>Add constant and improve null handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-e4e29fe6adb6eeae426abc0363010277925c0378a1b5ace82977584f38ee2a9a">+9/-9</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>MediaHelper.kt</strong><dd><code>Simplify null handling in video link</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-ccf8dd511f7d297a7024706d2557eb4d4f9a80ceb1906bae2dedfff563cb6c1d">+1/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>ReleaseDateHelper.kt</strong><dd><code>Add constants and improve null safety</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-f604577be6fbcc84e5e0d965c2e1a5d133282d379eca7af3863c9d70766051e2">+11/-9</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>GetDetailMovieInteractorTest.kt</strong><dd><code>Replace type casting with assertIs</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-9dacbd1a6645ed060a788a86e2b63ad7026f1b627253e60e27b3a43dd8465394">+3/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>GetTvDetailsInteractorTest.kt</strong><dd><code>Use assertIs for type checking</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-c876e91c1944a272d04589cfa5c13b1f6e89ae1622972c841476a9903b39df99">+4/-2</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>MyFavoriteMoviesFragment.kt</strong><dd><code>Improve null safety in undo action</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-5426fcd8992005b0d0105be6914e9a4de72dbabaccfa072328225a5e0a2bcd1e">+10/-9</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>MyFavoriteTvSeriesFragment.kt</strong><dd><code>Add null safety to undo operation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-d150843ad8ce61166963072038ae44e623a605a8e55cbbf4afb1d4d3044aa461">+10/-9</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>ItemWIdeAdapter.kt</strong><dd><code>Convert DiffCallback to single expressions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-6ecdc43701656be6a62e0a6fce3d4cf3fee9cc103be122f51baf5d2e138a36cc">+4/-12</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Error handling</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td><strong>SetRatingAction.kt</strong><dd><code>Add null safety check for RatingBar cast</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-b3ab6c8eedb88d04aafd72e338b95c5e53ff47317b4d02d1521c27407350c00a">+3/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr><tr><td><strong>Additional files</strong></td><td><details><summary>19 files</summary><table>
<tr>
  <td><strong>MovieHomeAdapter.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-6e9e44989216879b1f96c5003bbdd2fe667a915d90a9564fc74a495b002acd1f">+5/-12</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>TrendingAdapter.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-04bf4e4b4d6cb32794baceecfd02dfd4c6daa8e107a8b03b1fca8015608ae52a">+5/-12</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>TvAdapter.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-11e3aa26fecfa9314bf78d21c649b65362d3e250023377e28cf7bfc53a6772bf">+5/-12</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>DataDumpTest.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-14b66962af19f4e837c6c4d65f07f67fea52b78a384db7e039ba54c2d1fb313c">+82/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>DefaultPersonActivityTestHelper.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-9a3076489d36e57f0b25e0d88d98504785e28fcc13f036fae84a9c90a4edfb72">+71/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>PersonActivityTestHelper.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-31131e7c5f2a806a919c6866c1f66c7e26ab8229a5f6bd60d1d1e5b7614d6fa5">+20/-52</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>PersonActivityTestSetup.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-9ba7197b35f6063fccc1d6f9f7e651a87d83ff1d6a0817edd8b9a28f95fd7187">+0/-26</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>TestHelper.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-7ecfa2adf1daa38f08ae346680d9ff13294d79e9e0e05d80bc85ab4240000c62">+9/-78</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>PersonActivityImageDialogTest.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-e1fda346906ce2d74bcffa7e3d5bed9c8f27f28ef2cda692bce1dfc412b3ae30">+4/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>PersonActivityTest.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-55486c9377fb15d17ba8ab1f959e64bd21410901298e1635bb3b12c15c8088ee">+10/-11</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>PersonActivity.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-80a80ffccf445846a6d69c0345f3c2504e8521a6246d369fa94f00258d439249">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>DefaultFragmentTestHelper.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-33693af97004ade97b2511ce67353f07a1632fefa4af7c93f11c280577c9121c">+62/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>SearchFragmentTestHelper.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-428aec77490c96510b72ca71424b28e072f1517cae7b34a69f35575526aa9555">+30/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>SearchFragmentTest.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-d8f5b93a571263b2d0476de7036b22c1d687f2332d728cb5a0652d1049512588">+6/-38</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>SearchFragment.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-0e428d29bb342f7d7830610c1d5e88ac16acee9955f8e7fa8f4fdcacd855ab9b">+8/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>SearchRepositoryImplTestTwo.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-178cd660ffe668e2f6298736108f4665fa38e63820ed657b30eb2b755b96d7b2">+16/-14</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>SetupRecyclerViewTest.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-2c81db9203cc0f2525e57a2b9df18e413113f614c746693671c94151645585b3">+14/-11</a>&nbsp; </td>

</tr>

<tr>
  <td><strong>MyWatchlistMoviesFragment.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-26d56f45c1176ee0a203db94373937a3c0d73b44aa6bdaa7711832e1e36c6595">+10/-9</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>MyWatchlistTvSeriesFragment.kt</strong></td>
  <td><a href="https://github.com/waffiqaziz/BAZZ-Movies/pull/279/files#diff-e8a6b9a0df8a6d77d1d1ea942dff65dab360889b817c44c5cb2e10243ee27093">+10/-9</a>&nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

</details>

___

### CODE REVIEW

File: feature/person/src/main/kotlin/com/waffiq/bazz_movies/feature/person/ui/PersonActivity.kt [hunk 1]
```diff
@@ -152,8 +152,8 @@ class PersonActivity : AppCompatActivity() {
 
     binding.collapse.title = dataExtra.name ?: dataExtra.originalName ?: getString(not_available)
     val imageToLoad = if (!dataExtra.profilePath.isNullOrEmpty()) {
-      TMDB_IMG_LINK_POSTER_W500 + dataExtra.profilePath
       binding.ivPicture.contentDescription = "with_profile"
+      TMDB_IMG_LINK_POSTER_W500 + dataExtra.profilePath
```
Comment (waffiqaziz) [inline feature/person/src/main/kotlin/com/waffiq/bazz_movies/feature/person/ui/PersonActivity.kt:156]: - This code Fixed #278
